/**
1035 Password (20)（20 分）
To prepare for PAT, the judge sometimes has to generate random passwords for the users. The problem is that there are always some confusing passwords since it is hard to distinguish 1 (one) from l (L in lowercase), or 0 (zero) from O (o in uppercase). One solution is to replace 1 (one) by @, 0 (zero) by %, l by L, and O by o. Now it is your job to write a program to check the accounts generated by the judge, and to help the juge modify the confusing passwords.

Input Specification:

Each input file contains one test case. Each case contains a positive integer N (<= 1000), followed by N lines of accounts. Each account consists of a user name and a password, both are strings of no more than 10 characters with no space.

Output Specification:

For each test case, first print the number M of accounts that have been modified, then print in the following M lines the modified accounts info, that is, the user names and the corresponding modified passwords. The accounts must be printed in the same order as they are read in. If no account is modified, print in one line "There are N accounts and no account is modified" where N is the total number of accounts. However, if N is one, you must print "There is 1 account and no account is modified" instead.

Sample Input 1:

3
Team000002 Rlsp0dfa
Team000003 perfectpwd
Team000001 R1spOdfa
Sample Output 1:

2
Team000002 RLsp%dfa
Team000001 R@spodfa
Sample Input 2:

1
team110 abcdefg332
Sample Output 2:

There is 1 account and no account is modified
Sample Input 3:

2
team110 abcdefg222
team220 abcdefg333
Sample Output 3:

There are 2 accounts and no account is modified
**/
#include<stdio.h>
#include<iostream>
#include<string>
using namespace std;
struct node{
    string name,password;
    //这个bool值很关键噢
    bool isChanged;
}T[1010];
//判断一个人的密码是否需要修改，如果要修改的话就修改并且count++，如果不要修改的话就啥屁事也不要干。
//这里使用了引用，所以实参的值会修改
void changePassword(node& person,int& count){
    int plength = person.password.size();
    //遍历password看是否需要修改
    for(int i=0;i<plength;i++){
        if(person.password[i]=='1'){
            person.password[i] = '@';
            person.isChanged = true;
        }else if(person.password[i]=='l'){
            person.password[i] = 'L';
            person.isChanged = true;
        }else if(person.password[i]=='0'){
            person.password[i] = '%';
            person.isChanged = true;
        }else if(person.password[i]=='O'){
            person.password[i] = 'o';
            person.isChanged = true;
        }
    }

    //如果密码修改了，count就自增
    if(person.isChanged){
        count++;
    }
}
int main(){
    int N;
    cin>>N;
    //初始化
    for(int i=0;i<N;i++){
        cin>>T[i].name>>T[i].password;
        T[i].isChanged = false;
    }

    //count统计修改了密码的人数
    int count=0;

    //遍历所有学生看谁要修改密码
    for(int i=0;i<N;i++){
        changePassword(T[i],count);
    }

    //没有人要修改的话直接输出语句
    if(count==0){
        if(N>1){
            cout<<"There are "<<N<<" accounts and no account is modified"<<endl;
        }else{
            cout<<"There is 1 account and no account is modified"<<endl;
        }
    }else{
        //直接输出就好了
        cout<<count<<endl;
        for(int i=0;i<N;i++){
            if(T[i].isChanged){
                cout<<T[i].name<<" "<<T[i].password<<endl;
            }
        }
    }

    return 0;
}

